# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e6eaf9e2224f5f98af8d8a3d57ec5f23ba752a8f8b004b223028ff73729899f2297957ea78e5fb47ca645da2ea3e43859e421fde17e85fd4f876982d7b3af9cd

test:
  secret_key_base: af677b66b0489ad59390f44bd4950364befeef9b3f4dafa5344d051409aa7232901029285e60950768f032d1a1b9b53350c91189dd931c4bcb0579a4984349e1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
